# Generated by Django 6.1.1 on 2026-09-12 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TargetDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "device_role",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("laptop", "Laptop"),
                            ("mobile", "Mobile / Tablet"),
                        ],
                        default="laptop",
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("linux", "Linux"),
                            ("macos", "macOS"),
                            ("ios", "iOS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("cpu_model", models.CharField(blank=True, max_length=255, null=True)),
                ("total_ram_gb", models.FloatField(default=0.0)),
                ("total_disk_gb", models.FloatField(default=0.0)),
                ("is_active_directory", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TelemetryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("cpu_usage_pct", models.FloatField(default=-1.0)),
                ("ram_usage_pct", models.FloatField(default=-1.0)),
                ("disk_usage_pct", models.FloatField(default=-1.0)),
                ("cpu_temp_celsius", models.FloatField(default=-1.0)),
                (
                    "contextual_payload",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="MainWebApp.targetdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="MainWebApp__device__42f9d9_idx",
                    )
                ],
            },
        ),
    ]
